### ISSUE TITLE
[BUG] MSCLoader Pro not detecting mods

### ISSUE THREAD

**Issue by Daddy-Kermit** [MSCLoaderPro/MSCModLoaderPro#26] opened 2021-06-21 19:16 UTC
**Description**
MSCLoader not finding mods, output log says 0 mods detected, however has correct file location, reinstalled MSCLoader twice, reinstalled all mods twice, checked mods one at a time, nothing changed. only variables i can think of is custom file music, but that is all.

**To Reproduce**
Was unable to find variable reproducing, still havent gotten it to work at all.

**Screenshots**
![image](https://user-images.githubusercontent.com/86236345/122815531-6b277580-d28a-11eb-9a2d-250d9fb4ce2c.png)
![image](https://user-images.githubusercontent.com/86236345/122815537-6e226600-d28a-11eb-910a-12313cf6540c.png)

**output_log.txt**
[output_log.txt](https://github.com/MSCLoaderPro/MSCModLoaderPro/files/6688974/output_log.txt)

**Comment by Wampa842** [comment] 2021-06-25 16:19
It's not an issue with the loader. You have to extract extract the archives into the Mods folder.

**Comment by Tresquel** [comment] 2021-08-04 11:38
You have to extract the dlls to the mods location

**Comment by Athlon007** [comment] 2021-08-04 17:01
You must extract the .ZIP files into the Mods folder. Closing, as it's not a bug.

**Closed by Athlon007** 2021-08-04 17:01 UTC
